"""
Known roasting machine names from Artisan (artisan-for-QQ fork).
Full list from Config → Machine menu: includes/Machines/**/*.aset
Display name = folder + " " + filename (underscores → spaces).
"""

ARTISAN_MACHINES = [
    "Aillio Bullet R1",
    "Aillio Bullet R1 IBTS",
    "Aillio Bullet R2",
    "Ambex YM",
    "Arc 800",
    "Arc 800 RTD",
    "Arc S",
    "Arc S RTD",
    "Atilla GOLD plus 7''",
    "Atilla GOLD plus 7'' II",
    "Atilla GOLD plus 7'' II Control",
    "Atilla GOLD plus 7'' II Control Auto",
    "BC Roaster",
    "BeanGo Cube X",
    "Behmor 1kg",
    "BellaTW EVO",
    "Berto Autonics Control",
    "Berto D",
    "Berto Essential",
    "Berto One",
    "Berto R",
    "Besca Bee",
    "Besca Bee v2",
    "Besca BSC automatic",
    "Besca BSC full automatic",
    "Besca BSC manual v1",
    "Besca BSC manual v2",
    "Bideli Roaster",
    "BlueKing BK",
    "Brambati PLC",
    "Bühler RM 20 Playone",
    "Bühler RM 20 Simatic",
    "Bühler RM 20 Simatic Legacy",
    "Bühler RM 60-240",
    "Caparao Prime Line",
    "Carmomaq Caloratto 2.0",
    "Carmomaq Caloratto-Materatto Legacy",
    "Carmomaq Masteratto 2.0",
    "Carmomaq Speciatto 2.0",
    "Carmomaq Stratto 2.0",
    "Carmomaq Stratto Lab",
    "Coffed SR15 automatic",
    "Coffed SR15 manual delta",
    "Coffed SR25 automatic",
    "Coffed SR3 manual",
    "Coffed SR3 manual delta",
    "Coffed SR3 manual delta+ EBM-Papst",
    "Coffed SR3 manual delta+ Honeywell",
    "Coffed SR5 automatic",
    "Coffed SR5 manual",
    "Coffed SR5 manual delta",
    "Coffed SR5 manual delta+ EBM-Papst",
    "Coffed SR5 manual delta+ Honeywell",
    "Coffed SR60 automatic",
    "Coffee Machines Sale CMS-1",
    "Coffee Machines Sale CMS-6-30",
    "Coffee-Tech FZ94",
    "Coffee-Tech FZ94 EVO",
    "Coffee-Tech Ghibli Touch",
    "Coffee-Tech Ghibli USB",
    "Coffee-Tech Silon Touch",
    "Coffee-Tech Silon USB",
    "Coffeetool R",
    "Cogen Series C",
    "Cogen Series C V2",
    "Craftsmith Craft",
    "Craftsmith Craft air",
    "Craftsmith DIY",
    "Daetgen DR",
    "Daetgen DW",
    "Diedrich 4 Sensor Data Logging",
    "Diedrich 6 Sensor Data Logging",
    "Diedrich 6 Sensor Data Logging (Pre-2018)",
    "Diedrich CR",
    "Diedrich DR",
    "Dongyi BR",
    "Dongyi BY",
    "Dongyi DY",
    "Easyster 2Temp",
    "Easyster 3Temp",
    "Easyster AirPressure",
    "Easyster Smart",
    "Fabrica Roasters",
    "Froco FRA Advanced",
    "Froco FRA Improved",
    "Garanti GKPX",
    "Giesen Sample WPE",
    "Giesen Sample WPG",
    "Giesen W140A v1",
    "Giesen W140A v2",
    "Giesen W15A",
    "Giesen W15E",
    "Giesen W1A",
    "Giesen W1E",
    "Giesen W30A",
    "Giesen W30A PRO",
    "Giesen W45A",
    "Giesen W60A",
    "Giesen W6A",
    "Giesen W6A PRO",
    "Giesen W6E",
    "Giesen WxA",
    "Giesen WxA coarse",
    "Giesen WxA IR",
    "Giesen WxA IR Env",
    "Giesen WxA+",
    "Giesen WxA+ IR",
    "Giesen WxA+ IR Env",
    "Golden Roasters GR 2xEMKO",
    "Golden Roasters GR Automatic",
    "Golden Roasters GR Delta",
    "Golden Roasters GR Legacy",
    "Golden Roasters GR Manual",
    "Has Garanti HGS",
    "Has Garanti HSR",
    "HB Model S",
    "HB Standard",
    "Hive Roaster Data Dome",
    "Hottop KN-8828B-2K+",
    "Hottop TC4",
    "IKAWA HOME",
    "IKAWA PRO",
    "IKAWA PRO X",
    "IMF RM",
    "IMF RM control",
    "IMF RM legacy",
    "iRm Series Mitsubishi PLC",
    "iRm Series Omron PLC",
    "Joper PLC",
    "Kaldi Fortis",
    "Kaleido Legacy",
    "Kaleido Network",
    "Kaleido Serial",
    "KapoK USB",
    "KapoK USB Inlet",
    "Kirsch+Mausser PLC",
    "Kirsch+Mausser PLC control",
    "Kraffe PLC",
    "Kuban Supreme (Automatic)",
    "Kuban Supreme (Manual)",
    "Lilla PLC",
    "Loring Smart Roast",
    "Loring Smart Roast Auto",
    "Mill City Roasters Digital Control Panel 1000 C",
    "Mill City Roasters Digital Control Panel 1000 F",
    "Mill City Roasters Digital Control Panel 1200 C",
    "Mill City Roasters Digital Control Panel 1200 F",
    "Mill City Roasters Phidget",
    "Mill City Roasters Phidget & Delta controls (port on the back)",
    "Mill City Roasters Phidget & Delta controls (port on the right) C",
    "Mill City Roasters Phidget & Delta controls (port on the right) F",
    "Mill City Roasters Phidget & Shihlin controls (port on the back)",
    "Mill City Roasters Standard Control Panel (Delta) C",
    "Mill City Roasters Standard Control Panel (Delta) F",
    "Mill City Roasters Standard Control Panel (Fotek) C",
    "Mill City Roasters Standard Control Panel (Fotek) F",
    "Mugma 1000",
    "Mugma 2000",
    "Neuhaus Neotec PLC",
    "NOR A Series",
    "NOR Extension MODBUS",
    "NOR N Series",
    "Nordic DeltaDTA",
    "Nordic DeltaDTK",
    "Nordic PLC",
    "Opp MR",
    "OTesla Roaster",
    "Ozturk OKS",
    "Petroncini TT ASEM",
    "Petroncini TT Maestro Avantgarde",
    "Petroncini TT Maestro i06 Avantgarde",
    "Petroncini TT Traditional",
    "Phidget USB 1048 Databridge 2xTC",
    "Phidget VINT Ambient Modules",
    "Phidget VINT TMP1101 2xTC",
    "Phidget VINT TMP1200 2xRTD",
    "Phoenix ORO",
    "Phoenix ORO PXF",
    "Plugin Roast 2.0",
    "Primo Xr",
    "Prisma PLC",
    "Prisma USB",
    "Proaster 2Temp",
    "Proaster 3Temp",
    "Proaster AirPressure",
    "Proaster THCR-01A",
    "Probat G UG",
    "Probat G UG control",
    "Probat P Series III",
    "Probat Probatone",
    "Probat Probatone 7''",
    "Probat Sample Roaster",
    "Prometheus Ignis",
    "R & R Automatic",
    "R & R Manual",
    "Rasco Mac CRMA",
    "Roastmax Roasters",
    "Rolltech EL",
    "San Franciscan SF",
    "San Franciscan SF Eurotherm",
    "Santoker 1xPXR",
    "Santoker 2xPXF",
    "Santoker 2xPXR",
    "Santoker Cube Bluetooth",
    "Santoker Cube Bluetooth PID",
    "Santoker Q + X Series Bluetooth",
    "Santoker Q + X Series WiFi",
    "Santoker R Master Series Bluetooth",
    "Santoker R Master Series WiFi",
    "Santoker R Series Bluetooth",
    "Santoker R Series USB",
    "Sedona Elite Roaster",
    "Sedona Elite Roaster 2in1",
    "Sedona Elite Roaster PXF",
    "Sivetz SRM",
    "Sivetz SRM legacy",
    "Sweet Coffee Italia Gemma 26-30IND",
    "Sweet Coffee Italia Gemma 2IND",
    "Sweet Coffee Italia Gemma 6-8IND",
    "Titanium TGX",
    "Toper PLC",
    "Toper PLC Control",
    "Toper USB",
    "Tostabar Genius",
    "TRINITAS T2",
    "TRINITAS T2 air",
    "TRINITAS T2 legacy",
    "TRINITAS T7",
    "TRINITAS T7 gas",
    "TRINITAS T7 legacy",
    "Twino Ozstar",
    "Typhoon Hybrid",
    "Typhoon Shoproaster",
    "US Roaster Corp RTU",
    "VNT Phidget",
    "VNT PID",
    "Vortecs Pro",
    "Wintop WB",
    "Wintop WK",
    "Wintop WS 2in1",
    "Wintop WS Fuji",
    "Yangchia 8xxn",
    "Yoshan BR",
    "Yoshan BY",
    "Yoshan DY",
    "Yoshan EC-500",
    "Yoshan YS",
]
